language: java
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
jdk:
- oraclejdk8
script: mvn install test -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: heroku
  api_key:
    secure: nKxSHeoUaoUNb9FyN3rv6jjxVlr2IqtcPpfo4qy6LrGKUDr23cGi46F13AXghKyI9N2kL67H7cQrICEiNLozAhAMtO4DCnPVKmyNjyaRhUiQet7d9U8dmtq86sxQH8Oo5sP8D/cLdZ1cdHfljoa2yFvMfN6ZJ3A2bpEZF09UwJDPiGFJB7MmJR6HPPKQzfifx1FgF+3XF6+rDR3VQXTY4UIprNVvDlPYnOtWjJOPRzobM/vadF+6U4do3Q+zJXVmtD4AqUJ+XCXPz+sTyvcI8D1MJvilLvpaCNGByVJumLT49xCGD5rjQseY3R38HaVnDH7R/+PX5xrJr7V1YiV6tNN+A09+aOO3p01HYHlKcKjJUE8JUewjqArbD8fb4f/AlwHS3I9aNt6RF2xKj7Bp1X2uHCbtUARar99OLL9Pf8WJhM6wBuj3q0qa4krC8YrCPj+NzSVOJPAiv6EmTf1f9GB8aW9uiSWZVaME8xH2toY8Ggn2O+g85YK/Wno9cCa7MZ+8ddUduQ18eeen0da7AV5Owoc8bSf+f7lCeUMctti0cVIMAC7ir50KEZBXw4WnDVyPjqv1ODqpmKN0jM8KAVXOFKaJYM6GeyRvAKtfxINH0pN8HX4GaLEa5AfGTWDZ/Rl5qUUu9xVxkBXkwmuSzWlu7OabHJ1Hx9l7dLnXL1k=
  app: validation-manager
  on:
    repo: javydreamercsw/validation-manager
    branch: test-management
