language: java
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
jdk:
- oraclejdk8
script: mvn install test -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: openshift
  user: javydreamercsw
  password:
    secure: BlcPfNEWtbKBFRVebAQtWHcvp7cSXO4FJxa6Ew35lVX57qaxdgX791lqHaCFP76NbcMIXRpB1c0zOPL9n4jX1zoPnmrGKpvOMB44nyyucRqAehgXkEa/ozEFD3NgZZae5Vjvvjfv3/KuACgLrhws1xV2Utv6C2GgQkcONcK1JIjWwxPXr7c+ymnyCQvBRV+Xvz4dPtA26+QyA/Z1AefE9mZ6vqxDF56+VeLKTn+WevX31GcF3zeXcrjnqLF7ZHGPRSPtq/0bZV54frRyFpKJVYNnfXbIL2w6+yX/be3RT77ZiZXM0sjBOakElPnqOKmyOjZvxA0LMpBSIWcqXECTtwLZS8wRgvItw04kcQglij4OTJ1AAvZxrQzVToSLl7UFPpjmhWzhzJ9BjN6gtXQ2itIUK9Rdu2Z5yfONncRTMgbRTrOOU2CUGI5TXRu3Uz3TlWuOjFils/pExLlRMLrXO4GgyAf3ucm6DSTIktX6bbUXz+1OEWSPTw2Aln2I2NMtAB5taOjv4IhDtDxXQ5Znuf6FZrOoU5LQo/bzcTjXiUjFsCrt68x7nKeLGWHmkpOyMLmUFozKQb86rJ0s9AwQDdzdnyDpaWStvu9wPJ6ODhzDhjIm+VYb1gMAKDKe4AgaRZmeKNJXg7MR+uToVhRG4r3iZwpIRcMJNB9HBp7Jnrc=
  app: vm
  domain: javydreamercsw
  on:
    repo: javydreamercsw/validation-manager
    branch: test-management
